<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>grog</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Prefer32Bit>True</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Grog.version.txt" />
    <EmbeddedResource Include="Grog.version.txt" LogicalName="Grog.version.txt" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core">
      <HintPath>../../../.dotnet/shared/Microsoft.NETCore.App/10.0.12/System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>